package com.finance.budget.domain.expense;

public enum ExpenseCategory {
  FOOD,
  HOUSING,
  TRANSPORTATION,
  HEALTH_AND_MEDICINE,
  ENTERTAINMENT_AND_LEISURE,
  CLOTHES_AND_SHOES,
  EDUCATION,
  COMMUNICATIONS_AND_THE_INTERNET,
  FINANCIAL_EXPENSES,
  CHARITY,
  FAMILY_AND_CHILDREN,
  PETS,
  BEAUTY_AND_CARE,
  APPLIANCES_AND_ELECTRONICS,
  LONG_TERM_INVESTMENTS,
  INSURANCE,
  TAXES,
  REPAIRS_AND_MAINTENANCE,
  GIFTS_AND_HOLIDAYS,
  WORK_EXPENSES,
  ENTERTAINMENT_AND_HOBBIES,
  SPORTS_AND_FITNESS,
  RESTAURANTS_AND_CAFES,
  UNEXPECTED_EXPENSES,
  ANOTHER
}
