spring:
  profiles:
    default: dev
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  sql:
    init:
      platform: postgres
logging:
  level:
    org.springframework.web: trace
    org.springframework.security: debug
    com.finance.logger: debug
server:
  port: 8001
