spring:
  profiles:
    default: dev
  application:
    name: analysis-service
logging:
  level:
    org.springframework.http.converter.json: debug
    org.springframework.web: debug
    org.springframework.security: debug
    com.finance.logger: debug
server:
  port: 8003